- data/vaults/0x19D3364A399d251E894aC732651be8B0E4e85001.json
- data/vaults/0x1b905331F7dE2748F4D6a0678e1521E20347643F.json
- data/vaults/0x3D980E50508CFd41a13837A60149927a11c03731.json
- data/vaults/0x4560b99C904aAD03027B5178CCa81584744AC01f.json
- data/vaults/0x490bD0886F221A5F79713D3E84404355A9293C50.json
- data/vaults/0x528D50dC9a333f01544177a924893FA1F5b9F748.json
- data/vaults/0x59518884EeBFb03e90a18ADBAAAB770d4666471e.json
- data/vaults/0x595a68a8c9D5C230001848B69b1947ee2A607164.json
- data/vaults/0xa9fE4601811213c340e850ea305481afF02f5b28.json
- data/vaults/0xe11ba472F74869176652C35D30dB89854b5ae84D.json
- schema/token.json
- schema/vault.json
* override APY for several new and retired vaults
* add migration schema, apply it to relevant vaults (add old v2 WETH and DAI vaults)
* add ibXX vaults
> feat: several meta updates

- data/vaults/1/0x5f18C75AbDAe578b483E5F43f12a39cF75b973a9.json
- Add trusted vault migrator address as migration contract
> feat: add migration contract to usdc vault

- data/vaults/250/0x0A0b23D9786963DE69CB2447dC125c49929419d8.json
- data/vaults/250/0x0DEC85e74A92c52b7F708c4B10207D9560CEFaf0.json
- data/vaults/250/0x2C850cceD00ce2b14AA9D658b7Cad5dF659493Db.json
- data/vaults/250/0x637eC617c86D24E421328e6CAEa1d92114892439.json
- data/vaults/250/0xEF0210eB96c7EB36AF8ed1c20306462764935607.json
will need this https://github.com/yearn/yearn-sdk/pull/164 merging and released before this
> feat: enable displaying ftm apys

- data/vaults/1/0x16825039dfe2a5b01F3E1E6a2BBF9a576c6F95c4.json
- data/vaults/1/0x5e69e8b51B71C8596817fD442849BD44219bb095.json
- data/vaults/1/0x801Ab06154Bf539dea4385a39f5fa8534fB53073.json
- data/vaults/1/0xBCBB5b54Fa51e7b7Dc920340043B203447842A6b.json
- data/vaults/1/0xF59D66c1d593Fb10e2f8c2a6fD2C958792434B9c.json
included NEW override for vaults currently showing 0% due to API issues
> feat: add new curve vaults

- data/vaults/250/0x357ca46da26E1EefC195287ce9D838A6D5023ef3.json
override APY for now with NEW for frax vault
> feat: new override for FRAX vault

- data/vaults/1/0xd88dBBA3f9c4391Ee46f5FF548f289054db6E51C.json
for some weird reason dola wanted it's own pr (wouldn't commit to the same branch, made it's own new one twice...)
> [WEB-1106-116] fix: apy update for DOLA

- data/tokens/1/0x3D229E1B4faab62F621eF2F6A610961f7BD7b23B.json
- data/tokens/1/0x3b6831c0077a1e44ED0a21841C3bC4dC11bCE833.json
- data/tokens/1/0x87650D7bbfC3A9F10587d7778206671719d9910D.json
- data/tokens/1/0xBaaa1F5DbA42C3389bDbc2c9D2dE134F5cD0Dc89.json
- data/tokens/1/0xFbdCA68601f835b27790D98bbb8eC7f05FDEaA9B.json
EUR-USDC, EURTUSD, OUSD, d3pool, and ibbtc
> [WEB-1119-121] fix: added descriptions for underlying tokens

- data/strategies/250/ScreamFolding.json
- data/tokens/250/0x1E4F97b9f9F913c46F1632781732927B9019C68b.json
- data/tokens/250/0x3129662808bEC728a27Ab6a6b9AFd3cBacA8A43c.json
- data/tokens/250/0x321162Cd933E2Be498Cd2267a90534A804051b11.json
- data/tokens/250/0x468003B688943977e6130F4F68F23aad939a1040.json
- data/tokens/250/0x74b23882a30290451A17c44f4F05243b6b58C76d.json
- data/vaults/250/0x0446acaB3e0242fCf33Aa526f1c95a88068d5042.json
- data/vaults/250/0x1b48641D8251c3E84ecbe3f2bD76B3701401906D.json
- data/vaults/250/0xCe2Fc0bDc18BD6a4d9A725791A3DEe33F3a23BB7.json
- data/vaults/250/0xD3c19eB022CAC706c898D60d756bf1535d605e1d.json
- data/vaults/250/0xd817A100AB8A29fE3DBd925c2EB489D67F758DA9.json
DOLA, CRV, USDT, WETH, WBTC new vaults and scream folding strategies
> [WEB-1145-123] feat: update with new vaults, tokens, and strategies

- data/strategies/1/InverseSushiReinvest.json
- data/strategies/1/LiquityStabilityPool.json
Created new meta for:\
\-SushiBar and Inverse finance strategy\
\-LUSD (liquity stability pool) strategy
> [WEB-1143-122] feat: add strategy description

- data/vaults/250/0x0446acaB3e0242fCf33Aa526f1c95a88068d5042.json
- data/vaults/250/0xCe2Fc0bDc18BD6a4d9A725791A3DEe33F3a23BB7.json
- data/vaults/250/0xD3c19eB022CAC706c898D60d756bf1535d605e1d.json
- data/vaults/250/0xd817A100AB8A29fE3DBd925c2EB489D67F758DA9.json
Reverts yearn/yearn-meta#128, APRs are not calculated as expected :(
> fix: revert [WEB-1157-128] override for four vaults

- data/vaults/250/0x0446acaB3e0242fCf33Aa526f1c95a88068d5042.json
- data/vaults/250/0x148c05caf1Bb09B5670f00D511718f733C54bC4c.json
- data/vaults/250/0x1b48641D8251c3E84ecbe3f2bD76B3701401906D.json
- data/vaults/250/0x357ca46da26E1EefC195287ce9D838A6D5023ef3.json
- data/vaults/250/0xCe2Fc0bDc18BD6a4d9A725791A3DEe33F3a23BB7.json
- data/vaults/250/0xD3c19eB022CAC706c898D60d756bf1535d605e1d.json
- data/vaults/250/0xd817A100AB8A29fE3DBd925c2EB489D67F758DA9.json
Use numbers calculated from scripts instead of API, which is lagging.
> [WEB-1158-130] feat: manual override for new fantom vault APYs

- data/vaults/250/0x0446acaB3e0242fCf33Aa526f1c95a88068d5042.json
- data/vaults/250/0x148c05caf1Bb09B5670f00D511718f733C54bC4c.json
- data/vaults/250/0x1b48641D8251c3E84ecbe3f2bD76B3701401906D.json
- data/vaults/250/0x357ca46da26E1EefC195287ce9D838A6D5023ef3.json
- data/vaults/250/0xCe2Fc0bDc18BD6a4d9A725791A3DEe33F3a23BB7.json
- data/vaults/250/0xD3c19eB022CAC706c898D60d756bf1535d605e1d.json
- data/vaults/250/0xd817A100AB8A29fE3DBd925c2EB489D67F758DA9.json
update APYs on newer fantom vaults/strategies
> [WEB-1173-138] feat: update APYs

- data/tokens/42161/0x8e0B8c8BB9db49a46697F3a5Bb8A308e744821D2.json
pointing to https://arbitrum.curve.fi/tricrypto (rather than just curve.fi)
#171
> fix: update curveTriCrypto arbitrum website

- data/tokens/1/0x29059568bB40344487d62f7450E78b8E6C74e0e5.json
- data/vaults/1/0x790a60024bC3aea28385b60480f15a0771f26D09.json
added 0x790a60024bC3aea28385b60480f15a0771f26D09
as the vault
added 0x29059568bB40344487d62f7450E78b8E6C74e0e5
as the token
> fix: add yfi-eth to yearn meta

- data/protocols/250/0xDAO.json
- data/protocols/250/Beethoven-x.json
- data/protocols/250/CurveFinance.json
- data/protocols/250/EsterFinance.json
- data/protocols/250/GeistFinance.json
- data/protocols/250/IronBank.json
- data/protocols/250/Scream.json
- data/protocols/250/SolidexFinance.json
- data/protocols/250/SpiritSwap.json
- data/protocols/250/Spookyswap.json
- data/protocols/250/Tarot.json
Test run for the Portuguese translation of all files inside _data/protocols/250_
> Update PT for "data/protocols/250"

- data/protocols/1/Aave.json
i translated into japanese. thanks
> translation(protocol): aave

- data/protocols/1/1inch.json
i translated 1inch into japanese, thanks :)
> translation(protocol): 1inch

- data/vaults/1/0x5c0A86A32c129538D62C106Eb8115a8b02358d57.json
ovverride current APY (which may be broken) in favor of "new"
> fix: curve rocket APY override

- data/protocols/1/AlphaHomora.json
I translated Alpha Homora description into japanese. thanks.
> translation(protocol): Alpha Homora

- data/protocols/1/Balancer.json
I translated Balancer description into japanese. thanks.
> translation(protocol): Balancer

- data/protocols/1/1inch.json
- data/protocols/1/Aave.json
- data/protocols/1/AlphaHomora.json
- data/protocols/1/Balancer.json
- data/protocols/1/CompoundFinance.json
- data/protocols/1/ConvexFinance.json
- data/protocols/1/CreamFinance.json
- data/protocols/1/CurveFinance.json
- data/protocols/1/FiatDAO.json
- data/protocols/1/Hegic.json
- data/protocols/1/IdleFinance.json
- data/protocols/1/InverseFinance.json
- data/protocols/1/IronBank.json
- data/protocols/1/KeeperDAO.json
- data/protocols/1/LeagueDAO.json
- data/protocols/1/Liquity.json
- data/protocols/1/MakerDAO.json
- data/protocols/1/MushroomFinance.json
- data/protocols/1/NotionalFinance.json
- data/protocols/1/PoolTogether.json
- data/protocols/1/Sushi.json
- data/protocols/1/Synthetix.json
- data/protocols/1/Tokemak.json
- data/protocols/1/Universe.json
- data/protocols/1/VesperFinance.json
- data/protocols/1/dydx.json
translated files on protocol (Ehereum-FTM) to Turkish
> Protocols edit

- data/vaults/1/0x9d409a0A012CFbA9B15F6D4B36Ac57A46966Ab9a.json
- Remove yvBoost apy override now that has been harvested enough times
> feat: remove yvboost apy override

- data/tokens/250/0x2dd7C9371965472E5A5fD28fbE165007c61439E1.json
- data/tokens/250/0x58e57cA18B7A47112b877E31929798Cd3D703b0f.json
- data/tokens/250/0xD02a30d33153877BC20e5721ee53DeDEE0422B2F.json
Curve fantom websites now direct to fantom vaults
> fix: fantom websites

- data/strategies/250/0xDAOReinvest.json
- data/strategies/250/BeethovenJointProvider.json
- data/strategies/250/BeethovenSingleSided.json
- data/strategies/250/BeethovenfBeetsStaking.json
- data/strategies/250/BooXbooHec.json
- data/strategies/250/CurveGauge.json
- data/strategies/250/EsterReinvest.json
- data/strategies/250/GeistBorrow.json
- data/strategies/250/GeistFolding.json
- data/strategies/250/KashiLender.json
- data/strategies/250/LenderOptimizer.json
- data/strategies/250/MasterchefGenericReinvest.json
- data/strategies/250/ScreamFolding.json
- data/strategies/250/SolidexJointProvider.json
- data/strategies/250/SolidexSingleSidedStable.json
- data/strategies/250/SolidexSingleSidedVolatile.json
- data/strategies/250/SpiritJointProviderHedged.json
- data/strategies/250/SpookyJointLiquidityProvider.json
- data/strategies/250/SpookyJointProviderHedged.json
- data/strategies/250/SpookyReinvest.json
- data/strategies/250/SpookyStakerReinvest.json
- data/strategies/250/TarotReinvest.json
- data/strategies/250/VeDAOReinvest.json
> translate-data-strategies-250-in-Chinese

- data/vaults/1/0x8b9C0c24307344B6D7941ab654b2Aeee25347473.json
Zapper doesn't support EURN zapping, need to disable.
> fix: EURN zap in out

- data/vaults/250/0xA97E7dA01C7047D6a65f894c99bE8c832227a8BC.json
It's been harvested multiple times so apy is good to show
> feat: remove crv mim 3pool new apy

- data/tokens/1/0x828b154032950C8ff7CF8085D841723Db2696056.json
- data/vaults/1/0x5faF6a2D186448Dfa667c51CB3D695c7A6E52d8E.json
> feat: add lido yvault

- data/vaults/1/0x1025b1641d1F23C289412Dd5E5701e9810103a93.json
- data/vaults/1/0x2e5c7e9B1Da0D9Cb2832eBb06241d18552A85400.json
- data/vaults/1/0x341bb10D8f5947f3066502DC8125d9b8949FD3D6.json
- data/vaults/1/0x6B5ce31AF687a671a804d8070Ddda99Cab926dfE.json
- data/vaults/1/0x9A39f31DD5EDF5919A5C0c2433cE053fAD2E0336.json
- data/vaults/1/0xE5eDcE53e39Cbc6d819E2C340BCF295e0084ff7c.json
- data/vaults/1/0xF6B9DFE6bc42ed2eaB44D6B829017f7B78B29f88.json
- data/vaults/1/0xb09F2a67a731466182518fae980feAe96479d80b.json
- Curve STG-USDC
- Curve ibAUD-USDC
- Curve ibGBP-USDC
- Curve ibCHF-USDC
- Curve ibEUR-USDC
- Curve ibJPY-USDC
- Curve ibKRW-USDC
- Curve KP3R-ETH
> feat: add new vault token jsons

- data/strategies/42161/CurveGauge.json
- data/tokens/42161/0x7f90122BF0700F9E7e1F688fe926940E8839F353.json
- data/vaults/42161/0x49448d2B94fb9C4e41a30aD8315D32f46004A34b.json
Update yearn-meta for newly endorsed vault
https://arbitrum.curve.fi/2pool
https://yearn.finance/#/vault/0x49448d2B94fb9C4e41a30aD8315D32f46004A34b
> feat: arbitrum 2crv new vault

- data/vaults/1/0x5faF6a2D186448Dfa667c51CB3D695c7A6E52d8E.json
- data/vaults/250/0xCbCaF8cB8cbeAFA927ECEE0c5C56560F83E9B7D9.json
- data/vaults/250/0xF137D22d7B23eeB1950B3e19d1f578c053ed9715.json
- retire concentrated stETH vault
- update manual APYs for fantom curve vaults
> chore: updates

- data/vaults/1/0x1025b1641d1F23C289412Dd5E5701e9810103a93.json
- data/vaults/1/0x2e5c7e9B1Da0D9Cb2832eBb06241d18552A85400.json
- data/vaults/1/0x6B5ce31AF687a671a804d8070Ddda99Cab926dfE.json
- data/vaults/1/0x9A39f31DD5EDF5919A5C0c2433cE053fAD2E0336.json
- data/vaults/1/0xE5eDcE53e39Cbc6d819E2C340BCF295e0084ff7c.json
- data/vaults/1/0xF6B9DFE6bc42ed2eaB44D6B829017f7B78B29f88.json
- data/vaults/1/0xb09F2a67a731466182518fae980feAe96479d80b.json
change new vault types to regular if they are not errored in the api.
> fix: update new vaults to regular
